---
apiVersion: apps/v1
kind: Deployment                 
metadata:
  name: loyalty-reg  
  namespace: loyalty         
spec:
  replicas: 3                    
  selector:
    matchLabels:
      app: loyalty-reg
  template:                      
    metadata:
      labels:                    
        app: loyalty-reg 
    spec:                        
      containers:
      - name: loyalty-reg
        image: harbor.hardtophotels.com/hardtop/loyalty-reg:1.8
        env:
        - name: MONGO_HOST
          value: "mongo"
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_USER
          value: root
        - name: MONGO_PASS
          value: ""
        - name: MONGO_TLS
          value: ""
        imagePullPolicy: Always
        ports:
          - containerPort: 8080  
        livenessProbe:           
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:   
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1    
---
apiVersion: v1
kind: Service
metadata:
  name: reg-svc
  namespace: loyalty
  labels:
    app: loyalty-reg
spec:
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
  selector:
    app: loyalty-reg
